import { type User } from "./ColaboradoresTableTypes.type";

export const colaboradoresMockData: User[] = [
  {
    id: "1",
    email: "maria.gonzalez@empresa.com",
    nombre: "María González",
    posicion: "Gerente de Recursos Humanos",
    sueldo: 45000,
    clave_Interbancaria: "012180000118359719",
    banco: "BBVA Bancomer",
    activo: true,
    activo_Imss: true,
    jefe_inmediato: "Carlos Mendoza",
  },
  {
    id: "2",
    email: "juan.rodriguez@empresa.com",
    nombre: "Juan Rodríguez",
    posicion: "Desarrollador Senior",
    sueldo: 38000,
    clave_Interbancaria: "014180000118359720",
    banco: "Santander",
    activo: true,
    activo_Imss: true,
    jefe_inmediato: "Ana López",
  },
  {
    id: "3",
    email: "ana.lopez@empresa.com",
    nombre: "Ana López",
    posicion: "Líder Técnico",
    sueldo: 42000,
    clave_Interbancaria: "002180000118359721",
    banco: "Banorte",
    activo: true,
    activo_Imss: true,
    jefe_inmediato: "Carlos Mendoza",
  },
  {
    id: "4",
    email: "carlos.mendoza@empresa.com",
    nombre: "Carlos Mendoza",
    posicion: "Director de Tecnología",
    sueldo: 65000,
    clave_Interbancaria: "072180000118359722",
    banco: "HSBC",
    activo: true,
    activo_Imss: true,
    jefe_inmediato: "Patricia Silva",
  },
  {
    id: "5",
    email: "lucia.martinez@empresa.com",
    nombre: "Lucía Martínez",
    posicion: "Diseñadora UX/UI",
    sueldo: 32000,
    clave_Interbancaria: "012180000118359723",
    banco: "BBVA Bancomer",
    activo: true,
    activo_Imss: false,
    jefe_inmediato: "Ana López",
  },
  {
    id: "6",
    email: "pedro.hernandez@empresa.com",
    nombre: "Pedro Hernández",
    posicion: "Analista de Datos",
    sueldo: 35000,
    clave_Interbancaria: "014180000118359724",
    banco: "Santander",
    activo: true,
    activo_Imss: true,
    jefe_inmediato: "Carlos Mendoza",
  },
  {
    id: "7",
    email: "sofia.torres@empresa.com",
    nombre: "Sofía Torres",
    posicion: "Contadora",
    sueldo: 28000,
    clave_Interbancaria: "002180000118359725",
    banco: "Banorte",
    activo: true,
    activo_Imss: true,
    jefe_inmediato: "María González",
  },
  {
    id: "8",
    email: "diego.castro@empresa.com",
    nombre: "Diego Castro",
    posicion: "Desarrollador Junior",
    sueldo: 25000,
    clave_Interbancaria: "072180000118359726",
    banco: "HSBC",
    activo: true,
    activo_Imss: true,
    jefe_inmediato: "Ana López",
  },
  {
    id: "9",
    email: "patricia.silva@empresa.com",
    nombre: "Patricia Silva",
    posicion: "CEO",
    sueldo: 80000,
    clave_Interbancaria: "012180000118359727",
    banco: "BBVA Bancomer",
    activo: true,
    activo_Imss: true,
    jefe_inmediato: "Junta Directiva",
  },
  {
    id: "10",
    email: "miguel.ruiz@empresa.com",
    nombre: "Miguel Ruiz",
    posicion: "Marketing Manager",
    sueldo: 40000,
    clave_Interbancaria: "014180000118359728",
    banco: "Santander",
    activo: false,
    activo_Imss: false,
    jefe_inmediato: "Patricia Silva",
  },
];
