export type CreateFacturaDto = {
  concepto: string;
  serie?: string | null;
  folio?: string | null;
  fechaEmision?: Date | null;
  subtotal: number;
  iva?: number | null;
  totalImpuestosTransladados?: number | null;
  totalImpuestosRetenidos?: number | null;
  total: number;
  uuid: string;
  rfcEmisor: string;
  nombreReceptor?: string | null;
  rfcReceptor: string;
  metodoPago?: string | null;
  moneda?: string;
  usoCfdi?: string | null;
  status: "VIGENTE" | "CANCELADA";
  nombreEmisor?: string | null;
  statusPago?: string | null;
  fechaPago?: Date | null;
  facturaUrl?: string | null;
  ingresadoPor?: string | null;
};
