export type FacturaDto = {
  id: string;
  tipoOrigen: "ingreso" | "egreso" | null;
  origenId: string | null;
  clienteProveedorId: string;
  clienteProveedorInfo: {
    id: string;
    nombre: string;
    rfc: string;
    direccion: string;
  } | null;
  clienteProveedor: string;
  concepto: string;
  monto: number;
  periodo: string;
  numeroFactura: string;
  folioFiscal: string;
  fechaEmision: string;
  fechaVencimiento: string;
  estado: "borrador" | "enviada" | "pagada" | "cancelada";
  formaPago: "transferencia" | "efectivo" | "cheque";
  rfcEmisor: string;
  rfcReceptor: string;
  direccionEmisor: string;
  direccionReceptor: string;
  numeroCuenta: string;
  clabe: string;
  banco: string;
  fechaPago: string | null;
  fechaRegistro: string;
  creadoPorId: string | null;
  creadoPorNombre: string | null;
  autorizadoPorId: string | null;
  autorizadoPorNombre: string | null;
  notas: string | null;
  ingresadoPor: string | null;
  ingresadoPorNombre: string | null;
  createdAt: string;
  updatedAt: string;
};

