export type RegistroHoraDto = {
  id: string;
  usuarioId: string;
  usuarioNombre: string;
  usuarioEmail: string;
  equipoJuridicoId: string;
  equipoJuridicoNombre: string;
  clienteProveedorId: string;
  clienteProveedorNombre: string;
  asuntoJuridicoId: string;
  asuntoJuridicoNombre: string;
  socioId: string;
  socioNombre: string;
  horas: number;
  descripcion: string | null;
  ano: number;
  semana: number;
  editable: boolean;
  hasActiveAuthorization: boolean;
  createdAt: string;
  updatedAt: string;
};
